services:
  dev:
    image: 'mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm'
    container_name: dev
    restart: unless-stopped
    command: tail -f /dev/null
    volumes:
      - ../..:/workspaces:cached
    environment:
      - NODE_ENV=development
      - NITRO_PORT=3000
